name: Buildpack Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'requirements.txt'
      - 'app.py'
  workflow_dispatch:

env:
  REGISTRY: acrworkshopcontainers2024.azurecr.io
  IMAGE_NAME: api-status

jobs:
  buildpack-build-and-test:
    name: Build with Paketo Buildpacks
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Login to Azure Container Registry
      uses: docker/login-action@v3.5.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Setup Pack CLI
      uses: buildpacks/github-actions/setup-pack@v5.1.0

    - name: Build with Buildpacks (Production)
      run: |
        pack build ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}-buildpack-prod \
          --builder paketobuildpacks/builder-jammy-base \
          --env BP_PYTHON_VERSION=3.11 \
          --env BP_ENVIRONMENT=production \
          --env BP_PYTHON_OPTIMIZE=true \
          --publish
