name: Docker Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.*'
      - 'requirements.txt'
      - 'app.py'
  workflow_dispatch:

env:
  REGISTRY: acrworkshopcontainers2024.azurecr.io
  IMAGE_NAME: api-status

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Login to Azure Container Registry
      uses: docker/login-action@v3.5.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image (Naive)
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile.naive
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}-naive
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-naive

    - name: Build and push Docker image (Production)
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}-prod
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-prod
